### ISSUE TITLE
Library does not seem to work in Arduino 1.8.7 ?

### ISSUE THREAD

**Issue by RubberChicken69** [MattFryer/Smoothed#1]
I have tried using this with a few different boards and get different messsages, here is the one when using Arduino Uno:

Build options changed, rebuilding all
Smoothed:18:1: error: 'Smoothed' is not a template

 Smoothed <float> mySensor; 

 ^

Smoothed:19:1: error: 'Smoothed' is not a template

 Smoothed <float> mySensor2;    

 ^

C:\Users\patri\Documents\Arduino\libraries\Smoothed\examples\Smoothed\Smoothed.ino: In function 'void loop()':

Smoothed:14:20: error: expected primary-expression before '=' token

 #define SENSOR_PIN = A0;    // The input pin for the sensor. In this example we are reading from an Arduino analogue pin. 

                    ^

C:\Users\patri\Documents\Arduino\libraries\Smoothed\examples\Smoothed\Smoothed.ino:55:41: note: in expansion of macro 'SENSOR_PIN'

   float currentSensorValue = analogRead(SENSOR_PIN);

                                         ^

Smoothed:55:51: error: expected primary-expression before ')' token

   float currentSensorValue = analogRead(SENSOR_PIN);

                                                   ^

exit status 1
'Smoothed' is not a template

**Comment by MattFryer** [comment]
Hi
I've just released a new version v0.2 which will hopefully work with Arduino IDE v1.8.7. Give it a try and let me know if it works OK for you.

Regards
Matt

**Comment by RubberChicken69** [comment]
Thanks Matt, this is working for me now.
