### ISSUE TITLE
Compiling Smoothed on STSTM32 gives warning

### ISSUE THREAD

**Issue by andreaswagner42** [MattFryer/Smoothed#11]
When compiling sources using Smoothed library I the the following warning:

In file included from lib/Signals/Signals.cpp:14:
.pio/libdeps/iRock_v1_1/Smoothed/src/Smoothed.h: In member function 'bool Smoothed<T>::clear() [with T = float]':
.pio/libdeps/iRock_v1_1/Smoothed/src/Smoothed.h:199:1: warning: control reaches end of non-void function [-Wreturn-type]
  199 | }

**Comment by MattFryer** [comment]
Good spot. Resolved in the next release.
