### ISSUE TITLE
Simple Fix to Remove Max Exponential Smoothing Restriction

### ISSUE THREAD

**Issue by DrafnicJS** [MattFryer/Smoothed#13]
Currently, 1 = max exponential smoothing
Swapped, Higher Value = more smoothing

If you swap "smoothReadingsFactor/100" for "1/smoothReadingsFactor" in the smoothed exponential calculation, it allows for an indefinite amount of smoothness, rather than being constrained to 0.01. Not Sure if this has any downstream issues, but seems to work well with a servo.

<img width="850" alt="image" src="https://user-images.githubusercontent.com/15956675/170074219-a603e9c5-7d72-4eba-a5da-6b8efbb40555.png">

**Comment by MattFryer** [comment]
Thanks for the suggestion. The change will be in the next release.
