### ISSUE TITLE
begin() without arguments gives error

### ISSUE THREAD

**Issue by gitterman** [MattFryer/Smoothed#15]
I have installed the latest rev. of the smoothed library.
The example says that begin() may be called without arguments, defaulting to (SMOOTHED_EXPONENTIAL, 10)
On my arduino nano, I do get an error, though, if I do not supply any argument to begin().
`error: no matching function for call to 'Smoothed<unsigned int>::begin()'`

**Comment by MattFryer** [comment]
Good spot. Resolved in the next release.
