### ISSUE TITLE
The smoothed.ino example fails while compiling for the NodeMCU board.

### ISSUE THREAD

**Issue by findux** [MattFryer/Smoothed#17]
The content of the error is as follows.

In file included from C:\Users\findu\AppData\Local\Temp\.arduinoIDE-unsaved2024118-15180-way3cj.h4d4\Smoothed\Smoothed.ino:12:
c:\Users\findu\OneDrive\Belgeler\Arduino\libraries\Smoothed\src/Smoothed.h: In member function 'bool Smoothed<T>::clear() [with T = float]':
c:\Users\findu\OneDrive\Belgeler\Arduino\libraries\Smoothed\src/Smoothed.h:199:1: error: control reaches end of non-void function [-Werror=return-type]
  199 | }
      | ^
cc1plus.exe: some warnings being treated as errors

exit status 1

Compilation error: exit status 1

**Comment by MattFryer** [comment]
Good spot. Resolved in the next release.

**Comment by findux** [comment]
Thanks.
