### ISSUE TITLE
Possible overflow of runningTotal

### ISSUE THREAD

**Issue by sdc53** [MattFryer/Smoothed#3]
Hi,
I'm studying your source and considering using it in my project, but I spotted a potential problem in smoothed.h in the get function, added a comment next to the problem line below.  I'd suggest a fix, but I'm not sure how to accomplish that without breaking the template goodness or having to make some assumptions about the datatype or array size.  
```
template <typename T>
T Smoothed<T>::get () {
  switch (smoothMode) {
    case SMOOTHED_AVERAGE : { // SMOOTHED_AVERAGE
      T runningTotal = 0;
    
      for (int x = 0; x < smoothReadingsNum; x++) {
//possible overflow of runningTotal with large arrays or values in T
        runningTotal += smoothReading[x];  
      }
```
I've got quite a bit of noise in the values I need to smooth so I was considering an array size of 100 or more, which with my values will overflow the running total.  I'd need a larger datatype for runningTotal, but it'd be wasteful to do that for the entire array.  Not sure about an elegant way to fix this, but it seems like a potential bug in some use cases, so I thought I'd let you know.  Thanks.

**Comment by MattFryer** [comment]
Hi,
Thanks for the feedback! You are correct that large data types or a large number of readings isn't really ideal and can cause issues when using the SMOOTHED_AVERAGE. Additionally you can very quickly consume a lot of memory on the controller and so I would recommend using SMOOTHED_EXPONENTIAL (a simple linear recursive exponential filter) instead. Although it still creates an array it is only a single value array and so will use a lot less memory. The included example shows its use.

It's should be possible to have a multi type template so the user could define a different data type for runningTotal. I'll put it on the enhancement list and give some thought to whether it offers any real advantage. Balancing advanced functionality over ease of use is always tricky.

Regards
Matt
