### ISSUE TITLE
It's somehow producing a negative result when set to int16_t

### ISSUE THREAD

**Issue by ghost** [MattFryer/Smoothed#5]
It doesn't like being set to int16_t as a variable type.  The code producing the serial plotted data is shown to the left in the image.  The values plotted are x and smoothed x. 

![image](https://user-images.githubusercontent.com/1443724/64838347-fbae2d80-d5af-11e9-8c8a-d86a94b0d101.png)

with the initialization line as 

```Smoothed <int16_t> movement;```

it produced the result as shown in the image.  The x value unsmoothed(blue line) is where it's supposed to be. But the smoothed value(red line) is showing as negative. 

Initializing the function as 

```Smoothed <int> movement```

makes it function as one would expect.  and produced the following result. 

![image](https://user-images.githubusercontent.com/1443724/64838417-4c258b00-d5b0-11e9-9ca0-e42be5159a02.png)

Showing both values in the same ballpark.   

I'm guessing that it's having issues somewhere converting the int16_t variable type internal. This code is running on an ESP8266. As I understand it,, int variables are stored differently on the ESP8266 which is probably where the problem lays.

**Comment by MattFryer** [comment]
I finally found some time to investigate this. I couldn't reproduce it on a NodeMCU which has an ESP8266 running the Smoothed example code tweaked to use int16_t instead of float.

**Comment by ghost** [comment]
If it was a problem with how the Espressif SDK handled int16_t variables, they may have resolved it in an update.  I dunno.  I shelved this project a while ago because I couldn't save the data to an SD card fast enough so I haven't touched it for quite some time. 

I dunno.  If you used the code as shown in my first image and it didn't do it, that'd be my guess. Espressif did something to the variable handling.

**Comment by MattFryer** [comment]
As I'm unable to recreate this then I'm closing the ticket. I will reopen should more reports occur.
