### ISSUE TITLE
reference to 'map' is ambiguous if used smoothhed.h

### ISSUE THREAD

**Issue by petervflocke** [MattFryer/Smoothed#6]
Hi,
You have used "using namespace std;" which may be considered as a bad practice.
Actually you even do not need std lib.
In arduino it leads to a conflict with built in function map.
Try to compile arduino program with "using namespace std;" and map function, you will get an error 
reference to 'map' is ambiguous, since std:map is different from arduino ones..

**Comment by MattFryer** [comment]
I couldn't recreate a conflict with map but you are correct that the reference to namespace std was legacy and should have been removed already. I've removed and the change will be in the next release.
