### ISSUE TITLE
Release new library version

### ISSUE THREAD

**Issue by AndreiBasangiu** [MattFryer/Smoothed#8]
Hi Matt,

I've been using your library to smooth out some voltage readings from a VESC motor controller. I was on the latest version (v1.1) and when using a buffer of ~3000 elements, the math simply didn't add up :) I then discovered there's a new commit that increases the buffer size to more than 255 elements.

Can you please consider releasing a v1.2 of the library? It may save other people's time.

I really like the simplicity and usefulness of your lib, it saved me quite some time by not having to write something similar from scratch. Thanks!

Andrei

**Comment by MattFryer** [comment]
Hi Andrei
I've just created a new release so it should appear as an update in Arduino library manager in an hour or so. I was meaning to get round to making a few other minor changes but haven't found the time.

Let me know if it fixes your issue.

Regards
Matt

**Comment by AndreiBasangiu-TomTom** [comment]
I got the new version today through the Arduino IDE, everything looks fine now.
Thanks for the responsiveness!
