### ISSUE TITLE
compilation on Arduino Nano gives warnings

### ISSUE THREAD

**Issue by gitterman** [MattFryer/Smoothed#9]
73:11: warning: unused variable 'lastValueStoredAvg' [-Wunused-variable]
     float lastValueStoredAvg = mySensor.getLast();
           ^~~~~~~~~~~~~~~~~~
:74:11: warning: unused variable 'lastValueStoredExp' [-Wunused-variable]
     float lastValueStoredExp = mySensor2.getLast();
           ^~~~~~~~~~~~~~~~~~
:12:0:
 In instantiation of 'bool Smoothed<T>::begin(byte, uint16_t) [with T = float; byte = unsigned char; uint16_t = unsigned int]':
39:37:   required from here
56:45: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (int thisReading = 0; thisReading < smoothReadingsNum; thisReading++) {
                                 ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
12:0:
 In instantiation of 'bool Smoothed<T>::clear() [with T = float]':
53:20:   required from here
184:45: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (int thisReading = 0; thisReading < smoothReadingsNum; thisReading++) {
                                 ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
In instantiation of 'T Smoothed<T>::get() [with T = float]':
65:49:   required from here
127:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (int x = 0; x < smoothReadingsNum; x++) {
                       ~~^~~~~~~~~~~~~~~~~~~
In member function 'bool Smoothed<T>::clear() [with T = float]':
199:1: warning: control reaches end of non-void function [-Wreturn-type]

**Comment by MattFryer** [comment]
Thanks. This is resolved in the next release.
